---
key: ""
autoclaim: true

vote_announcement: "§a{username} telah vote server!"

message_not_voted: "§cKamu belum vote hari ini!"
message_voted: "§aKamu sudah vote hari ini!"


commands:
  - "givemoney {username} 50000"
  - "mc key Knight 15 {username}"
...
